config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/discover', to: 'pages#discover', as: 'discover'
  get '/following', to: 'pages#following', as: 'following'
  get '/new_releases', to: 'pages#new_releases', as: 'new_releases'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def discover
  end

  def following
  end

  def new_releases
  end

  def components
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReleasyMockup</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/discover.html.erb
<div class="contain page-banner">
  <h1 class="header-lg">Discover</h1>
  <div class="underline-input-container">
    <svg width="33px" height="33px" viewBox="0 0 33 33" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="Page-1" stroke-width="1" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round">
            <g id="Desktop-HD-Copy-11" transform="translate(-78.000000, -361.000000)" stroke="#738881" stroke-width="2.5">
                <g id="Group" transform="translate(80.000000, 363.000000)">
                    <g id="Path">
                        <path d="M22.1923874,3.80761275 C27.2692043,8.88442963 27.2692043,17.1155706 22.1923874,22.1923874 C17.1155706,27.2692043 8.88442963,27.2692043 3.80761275,22.1923874 C-1.26920412,17.1155706 -1.26920412,8.88442963 3.80761275,3.80761275 C8.88442963,-1.26920412 17.1155706,-1.26920412 22.1923874,3.80761275"></path>
                        <path d="M29.0000001,29.0000001 L22.0000001,22.0000001"></path>
                    </g>
                </g>
            </g>
        </g>
    </svg>
    <input type="text" placeholder="Search an artist" class="hidden-input">
  </div>
</div>

<div class="contain">
  <div class="artists">
    <% 20.times do %>
      <%= render 'artists/artist' %>
    <% end %>
  </div>
</div>

app/views/pages/following.html.erb
<div class="contain page-banner">
  <h1 class="header-lg">Following</h1>
  <div class="underline-input-container">
    <svg width="33px" height="33px" viewBox="0 0 33 33" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="Page-1" stroke-width="1" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round">
            <g id="Desktop-HD-Copy-11" transform="translate(-78.000000, -361.000000)" stroke="#738881" stroke-width="2.5">
                <g id="Group" transform="translate(80.000000, 363.000000)">
                    <g id="Path">
                        <path d="M22.1923874,3.80761275 C27.2692043,8.88442963 27.2692043,17.1155706 22.1923874,22.1923874 C17.1155706,27.2692043 8.88442963,27.2692043 3.80761275,22.1923874 C-1.26920412,17.1155706 -1.26920412,8.88442963 3.80761275,3.80761275 C8.88442963,-1.26920412 17.1155706,-1.26920412 22.1923874,3.80761275"></path>
                        <path d="M29.0000001,29.0000001 L22.0000001,22.0000001"></path>
                    </g>
                </g>
            </g>
        </g>
    </svg>
    <input type="text" placeholder="Search an artist" class="hidden-input">
  </div>
</div>

<div class="contain">
  <div class="artists">
    <% 20.times do %>
      <%= render 'artists/artist' %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'components/home_banner' %>

<div class="bg-white">
  <div class="contain">
    <div class="feature">
      <div class="image-container">
        <%= image_tag 'feature.jpg' %>
      </div>
      <div class="info">
        <h3 class="header-md">Follow your favourite artist</h3>
        <p>Search for your favorite musicians using Spotify's database of artists.</p>
        <a href="" class="button button-primary">Find artists</a>
      </div>
    </div>
    <div class="feature">
      <div class="info">
        <h3 class="header-md">Follow your favourite artist</h3>
        <p>Search for your favorite musicians using Spotify's database of artists.</p>
        <a href="" class="button button-primary">Find artists</a>
      </div>
      <div class="image-container">
        <%= image_tag 'feature.jpg' %>
      </div>
    </div>
    <div class="feature">
      <div class="image-container">
        <%= image_tag 'feature.jpg' %>
      </div>
      <div class="info">
        <h3 class="header-md">Follow your favourite artist</h3>
        <p>Search for your favorite musicians using Spotify's database of artists.</p>
        <a href="" class="button button-primary">Find artists</a>
      </div>
    </div>
  </div>
</div>

<div class="bg-white" style="display: none">
  <div class="contain">
    <h1 class="header-lg">Header Lg</h1>
    <h2 class="header-md">Header Md</h2>

    <p>It prevents you from having to search through your code, trying to find all the places where you specified a certain number or name. Change the value of the variable and all the instances where it’s used will update along with it.</p>


    <a href="" class="button">Login</a>
    <a href="" class="button button-basic">Login</a>
    <a href="" class="button button-primary">Signup</a>
    <a href="" class="button button-highlight">Play on spotify</a>
    <a href="" class="button button-sm">Login</a>
    <a href="" class="button button-sm button-basic">Login</a>
    <a href="" class="button button-primary button-sm">Signup</a>
    <a href="" class="button button-highlight button-sm">Play on spotify</a>
  </div>
</div>

app/views/pages/new_releases.html.erb
<div class="contain page-banner">
  <h1 class="header-lg">New releases</h1>
</div>

<div class="contain">
  <h4 class="section-header">16th June</h4>
  <% 5.times do %>
    <%= render 'artists/artist_new_release', album: true %>
  <% end %>
  <h4 class="section-header">18th June</h4>
  <% 5.times do %>
    <%= render 'artists/artist_new_release', album: false %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.svg" %>
    Releasy
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Find artists", discover_path, class: "button button-basic" %>
        </li>
        <li class="nav-item">
          <%= link_to "Following", following_path, class: "button button-basic" %>
        </li>
        <li class="nav-item">
          <%= link_to "New releases", new_releases_path, class: "button button-basic" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Account", "#", class: "dropdown-item" %>
            <%= link_to "Connect spotify", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "button button-basic" %>
          <%= link_to "Signup", new_user_registration_path, class: "button button-primary" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>